ALTER TABLE account DROP INDEX IX_ACCOUNT_FIRSTNAME;
ALTER TABLE account DROP INDEX  IX_ACCOUNT_LASTNAME;

CREATE INDEX IX_ACCOUNT_FIRSTNAME ON account (first_name);
CREATE INDEX IX_ACCOUNT_LASTNAME ON account (last_name);